---
apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: default
  labels:
    juicefs.com/validate-secret: "true"
type: Opaque
stringData:
  name: juicefs
  metaurl: "postgres://<user>:<password>@<private endpoint ip of the db>:5432/<name of the database created>"
  storage: scw
  bucket: https://<bucket name>.s3.<region>.scw.cloud
  access-key: SCWXXXXXXXXXXXXXXXXXXX
  secret-key: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
